### ISSUE TITLE
deleteOld not working?

### ISSUE THREAD

**Issue by qkjosh** [Dragory/gulp-hash#22]
Hi, I can't seem to get deleteOld to work. I've set up a basic folder to test this out, and used virtually the same code as the example in the docs:

```js
var gulp = require('gulp');
var hash = require('gulp-hash');

gulp.task('js', function () {
  return gulp.src('./js/**/*.js')
    .pipe(hash()) 
    .pipe(gulp.dest('public/js')) 
    .pipe(hash.manifest('assets.json', {
      deleteOld: true,
      sourceDir: __dirname + '/public/js'
    })) 
    .pipe(gulp.dest('public')); 
});
```

The manifest gets updated and it adds the newly generated file, but the old one sticks around. 
Am I doing something wrong or is this just not working? Thanks!

**Comment by miladmeidanshahi** [comment]
same issue

**Comment by Dragory** [comment]
I sincerely apologize for not responding to this issue earlier.

This, and other problems that rely on an old/existing manifest file, are fixed by using the full relative path in the call to `hash.manifest()` (so `public/assets.json` in this case). As you noticed, the code example in the README was incorrect in this regard as well. I have corrected the example, and added a note about the manifest paths below it.
